Log in
IoT-Ausbildung/grade-calculator pull request #23
Opened 2024-04-12 13:14 UTC by Asman97

2024-04-15 15:56 UTC, dEisenbeiss commented on src/main/resources/application.properties
> +server.port=8082
please dont change the default port

2024-04-15 15:58 UTC, dEisenbeiss requested changes
Port must be changed back to default

2024-04-16 07:22 UTC, Asman97 commented on src/main/resources/application.properties
> +server.port=8082
port is set to default: 8080

2024-04-16 07:25 UTC, dEisenbeiss approved these changes

2024-04-16 07:35 UTC, merged